name: Dependabot
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/dependabot-core@0.135.x
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: '/'
          update-pattern: '**/*.yml'
